# Generated by Django 4.2.27 on 2026-01-26 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=50)),
                ('stage', models.CharField(choices=[('idea', 'Idea'), ('mvp', 'MVP'), ('launched', 'Launched'), ('scaling', 'Scaling')], max_length=20)),
                ('industry', models.CharField(max_length=100)),
                ('skills', models.JSONField(default=list)),
                ('looking_for', models.CharField(choices=[('cofounder', 'Co-founder'), ('feedback', 'Feedback'), ('users', 'Users'), ('networking', 'Just networking')], max_length=20)),
                ('personality_tags', models.JSONField(default=list)),
                ('current_goal', models.TextField()),
                ('is_online', models.BooleanField(default=False)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founder_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FounderConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connections', to='founders.founderprofile')),
                ('to_founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connections', to='founders.founderprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('from_founder', 'to_founder')},
            },
        ),
    ]
